import 'package:hive/hive.dart';
import 'package:my_chat/contactspage/contactusermodel.dart'; // Import your contact model

// ⚠️ This file will be generated by the command
part 'chatroommodel.g.dart';

@HiveType(typeId: 2) // <--- Unique ID 2 for Chat Room
class ChatRoomModel {
  @HiveField(0)
  final String chatId;

  @HiveField(1)
  final List<String> participants;

  @HiveField(2)
  final String? lastMessage;

  @HiveField(3)
  final int? lastMessageTime;

  @HiveField(4)
  final Map<String, int> clearedBy;

  ChatRoomModel({
    required this.chatId,
    required this.participants,
    required this.lastMessage,
    required this.lastMessageTime,
    required this.clearedBy,
  });

  factory ChatRoomModel.fromMap(Map<String, dynamic> map) {
    return ChatRoomModel(
      chatId: map['chatId'] ?? '',
      participants: List<String>.from(map['participants'] ?? []),
      lastMessage: map['lastMessage'],
      lastMessageTime: map['lastMessageTime'],
      // Safety check for the map
      clearedBy: map['clearedBy'] != null
          ? Map<String, int>.from(map['clearedBy'])
          : {},
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'chatId': chatId,
      'participants': participants,
      'lastMessage': lastMessage,
      'lastMessageTime': lastMessageTime,
      'clearedBy': clearedBy,
    };
  }
}

/// 🔥 NEW: We make the List Item saveable too! (ID: 3)
@HiveType(typeId: 3)
class ChatListItem {
  @HiveField(0)
  final ChatRoomModel chatroom;

  @HiveField(1)
  final usermodel otheruser; // It knows how to save this because ID: 1 exists!

  ChatListItem({required this.chatroom, required this.otheruser});
}
