import 'package:hive/hive.dart';

// ⚠️ This file will be generated by the command
part 'messagemodel.g.dart';

// 🟢 Hive ID 4 for the Enum
@HiveType(typeId: 4)
enum MessageType {
  @HiveField(0)
  text,
  @HiveField(1)
  image,
}

// 🟢 Hive ID 5 for the Model
@HiveType(typeId: 5)
class MessageModel {
  @HiveField(0)
  final String messageId;

  @HiveField(1)
  final String chatId;

  @HiveField(2)
  final String senderId;

  @HiveField(3)
  final String? text;

  @HiveField(4)
  final List<String> urls;

  @HiveField(5)
  final int timestamp;

  @HiveField(6)
  final MessageType messageType; // Hive knows this because we tagged the Enum above!

  @HiveField(7)
  final int starredAt;

  @HiveField(8)
  final List<String> starredBy;

  @HiveField(9)
  final bool isDeletedForEveryone;

  @HiveField(10)
  final List<String> deletedFor;

  @HiveField(11)
  final List<String> seenBy;

  MessageModel({
    required this.messageId,
    required this.chatId,
    required this.senderId,
    required this.messageType,
    required this.timestamp,
    this.text,
    this.urls = const [],
    this.starredAt = 0,
    this.starredBy = const [],
    this.isDeletedForEveryone = false,
    this.deletedFor = const [],
    this.seenBy = const [],
  });

  /* ---------------- FROM FIRESTORE ---------------- */
  factory MessageModel.fromMap(Map<String, dynamic> map) {
    return MessageModel(
      messageId: map['messageId'] ?? '',
      chatId: map['chatId'] ?? '',
      senderId: map['senderId'] ?? '',
      
      // Safety check for Enum
      messageType: MessageType.values.firstWhere(
        (e) => e.name == map['messageType'],
        orElse: () => MessageType.text,
      ),
      
      timestamp: map['timestamp'] ?? 0,
      text: map['text'],
      urls: List<String>.from(map['urls'] ?? []),
      starredAt: map['starredAt'] ?? 0,
      starredBy: List<String>.from(map['starredBy'] ?? []),
      isDeletedForEveryone: map['isDeletedForEveryone'] ?? false,
      deletedFor: List<String>.from(map['deletedFor'] ?? []),
      seenBy: List<String>.from(map['seenBy'] ?? []),
    );
  }

  /* ---------------- TO FIRESTORE ---------------- */
  Map<String, dynamic> toMap() {
    return {
      'messageId': messageId,
      'chatId': chatId,
      'senderId': senderId,
      'messageType': messageType.name,
      'text': text,
      'urls': urls,
      'timestamp': timestamp,
      'starredAt': starredAt,
      'starredBy': starredBy,
      'isDeletedForEveryone': isDeletedForEveryone,
      'deletedFor': deletedFor,
      'seenBy': seenBy,
    };
  }

  /* ---------------- COPY WITH ---------------- */
  MessageModel copyWith({
    String? text,
    List<String>? urls,
    int? starredAt,
    List<String>? starredBy,
    bool? isDeletedForEveryone,
    List<String>? deletedFor,
    List<String>? seenBy,
  }) {
    return MessageModel(
      messageId: messageId,
      chatId: chatId,
      senderId: senderId,
      messageType: messageType,
      timestamp: timestamp,
      text: text ?? this.text,
      urls: urls ?? this.urls,
      starredAt: starredAt ?? this.starredAt,
      starredBy: starredBy ?? this.starredBy,
      isDeletedForEveryone: isDeletedForEveryone ?? this.isDeletedForEveryone,
      deletedFor: deletedFor ?? this.deletedFor,
      seenBy: seenBy ?? this.seenBy,
    );
  }
}