// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkGLb22OYUSPaezkIFdBddEZMXqLUZBvY',
    appId: '1:1085637723112:web:6a3c7b77593d627def1a5d',
    messagingSenderId: '1085637723112',
    projectId: 'reddit-86621',
    authDomain: 'reddit-86621.firebaseapp.com',
    storageBucket: 'reddit-86621.firebasestorage.app',
    measurementId: 'G-STHSCCTRTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQVhxCyugbw1CV3ITHEwXp38N8Uh_Zh5w',
    appId: '1:1085637723112:android:4c881975ed239dccef1a5d',
    messagingSenderId: '1085637723112',
    projectId: 'reddit-86621',
    storageBucket: 'reddit-86621.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsU6n4wDQRHK2qlYFhCMBey0mgcuMhC20',
    appId: '1:1085637723112:ios:0634bc4431742afcef1a5d',
    messagingSenderId: '1085637723112',
    projectId: 'reddit-86621',
    storageBucket: 'reddit-86621.firebasestorage.app',
    iosBundleId: 'com.example.myChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsU6n4wDQRHK2qlYFhCMBey0mgcuMhC20',
    appId: '1:1085637723112:ios:0634bc4431742afcef1a5d',
    messagingSenderId: '1085637723112',
    projectId: 'reddit-86621',
    storageBucket: 'reddit-86621.firebasestorage.app',
    iosBundleId: 'com.example.myChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkGLb22OYUSPaezkIFdBddEZMXqLUZBvY',
    appId: '1:1085637723112:web:d7e727a138df4f79ef1a5d',
    messagingSenderId: '1085637723112',
    projectId: 'reddit-86621',
    authDomain: 'reddit-86621.firebaseapp.com',
    storageBucket: 'reddit-86621.firebasestorage.app',
    measurementId: 'G-C735J4GEZT',
  );
}
