import 'package:hive/hive.dart';

// ⚠️ This file will be generated by the command later
part 'contactusermodel.g.dart'; 

@HiveType(typeId: 1) // <--- NOTICE: This is ID 1 (Different from your profile)
class usermodel {
  @HiveField(0)
  final String uid;

  @HiveField(1)
  final String name;

  @HiveField(2)
  final String phonenumber;

  @HiveField(3)
  final String? about;

  @HiveField(4)
  final String? profileImageUrl;

  usermodel({
    required this.uid,
    required this.name,
    required this.phonenumber,
    this.about,
    this.profileImageUrl,
  });

  // Factory: From Map (Unchanged)
  factory usermodel.frommap(Map<String, dynamic> map) {
    return usermodel(
      uid: map['uid'] ?? '',
      name: map['name'] ?? '',
      phonenumber: map['phoneNumber'] ?? '', // Kept your logic here
      about: map['about'] ?? 'Hey there! I am using MyChat 💬',
      profileImageUrl: map['profileImageUrl'],
    );
  }

  // To Map (Unchanged)
  Map<String, dynamic> toMap() {
    return {
      'uid': uid,
      'name': name,
      'phoneNumber': phonenumber,
      'about': about,
      'profileImageUrl': profileImageUrl,
    };
  }

  // From Phone Contact (Unchanged)
  factory usermodel.fromphone(String name, String phonenumber) {
    return usermodel(uid: '', name: name, phonenumber: phonenumber);
  }

  // CopyWith (Unchanged)
  usermodel copyWith({
    String? uid,
    String? name,
    String? phonenumber,
    String? about,
    String? profileImageUrl,
  }) {
    return usermodel(
      uid: uid ?? this.uid,
      name: name ?? this.name,
      phonenumber: phonenumber ?? this.phonenumber,
      about: about ?? this.about,
      profileImageUrl: profileImageUrl ?? this.profileImageUrl,
    );
  }
}